version: '3.7'

services:
  app:
    image: "ihor8k/geofile:latest"
    container_name: "geofile_app"
    env_file:
      - .env.prod
    command: /app_start
    volumes:
      - static:/app/static
    networks:
      - net
    depends_on:
      - redis

  celery:
    image: "ihor8k/geofile:latest"
    container_name: "geofile_celery"
    command: /celery_start
    env_file:
      - .env.prod
    networks:
      - net
    depends_on:
      - redis

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/proxy_params:/etc/nginx/proxy_params
      - static:/usr/share/nginx/html/static
    depends_on:
      - app
      - celery
    networks:
      - net

  redis:
    build:
      context: ./redis
    privileged: true
    command: sh -c "./init.sh"
    networks:
      - net

volumes:
  static:

networks:
  net:
